### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by albertofwb** [Kxrr/nutstore-cli#1]
Traceback (most recent call last):
  File "cli.py", line 28, in cli
    client.check_conn()
  File "/home/albert/.local/lib/python2.7/site-packages/nutstore_cli/client/base.py", line 84, in check_conn
    self.ls()
  File "/home/albert/.local/lib/python2.7/site-packages/nutstore_cli/client/base.py", line 52, in ls
    return self._client.ls(self.np.real_path)
  File "/home/albert/.local/lib/python2.7/site-packages/easywebdav/client.py", line 176, in ls
    response = self._send('PROPFIND', remote_path, (207, 301), headers=headers)
  File "/home/albert/.local/lib/python2.7/site-packages/easywebdav/client.py", line 100, in _send
    raise OperationFailed(method, path, expected_code, response.status_code)
OperationFailed: Failed to list directory "/dav/home/albert/nutstore_test".
  Operation     :  PROPFIND /dav/home/albert/nutstore_test
  Expected code :  207 UNKNOWN, 301 Moved Permanently
  Actual code   :  409 Conflict

**Comment by Kxrr** [comment]
The `working_dir` means a remote diretory on nutstore, not a directory on your local machine like `/albert/nutstore_test`.

Maybe you want to check out this tutorial: https://github.com/Kxrr/nutstore-cli/blob/master/docs/tutorial.md
